services:
  mongodb:
    image: mongo:latest
    container_name: bestfoody_mongodb
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - bestfoody

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bestfoody_service
    env_file:
      - .env  
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - bestfoody

networks:
  bestfoody:

volumes:
  mongo_data:
